export const enum EstadosRemisionEnum {
  NUEVO = 'NUEVO',
  CANCELADO = 'CANCELADO',
  EMPALME = 'EMPALME',
  NO_ADMITIDO = 'NO_ADMITIDO',
  ADMITIDO = 'ADMITIDO',
  INGRESO = 'INGRESO',
  PENDIENTE_ADMITIR = 'PENDIENTE_ADMITIR',
  EGRESADO = 'EGRESADO'
}
