export enum ProcedimientoNovedadEnum {
    CURACIONES = 'CURACIONES',
    SONDAJES = 'SONDAJES',
    FOTOTERAPIAS = 'FOTOTERAPIAS',
    TOMA_MUESTRAS = 'TOMA_MUESTRAS',
    SECRECIONES = 'SECRECIONES',
    CANALIZACIONES = 'CANALIZACIONES',    
    SOPORTE_NUTRICIONALES = 'SOPORTE_NUTRICIONALES'
}