export const enum TipoProcedimientoEnum {

    CURACIONES = 'CURACIONES',
    SONDAJES = 'SONDAJES',
    FOTOTERAPIAS = 'FOTOTERAPIAS',
    SOPORTE_NUTRICIONAL = 'SOPORTE_NUTRICIONAL',
    ASPIRACION_SECRECIONES = 'ASPIRACION_SECRECIONES',
    TOMA_MUESTRAS = 'TOMA_MUESTRAS',
    CANALIZACIONES = 'CANALIZACIONES'
  }

