export const enum TipoPrestacionEnum {
    APLICACION_MEDICAMENTOS = 'AplicacionMedicamentos',
    CURACION_MAYOR = 'CuracionMayor',
    CURACION_MENOR = 'CuracionMenor',
    SONDAJE = 'Sondaje',
    SECRECION = 'Secrecion',
    TOMA_MUESTRA = 'TomaMuestra',
    SOPORTE_NUTRICIONAL = 'SoporteNutricional',
    CANALIZACION = 'Canalizacion',
    CATETER_PICC = 'CateterPICC',
    EDUCACION = 'Educacion',
    TERAPIAS_FISICAS = 'TerapiasFisicas',
    TERAPIAS_RESPIRATORIAS = 'TerapiasRespiratorias',
    TERAPIAS_FONOAUDIOLOGIA = 'TerapiasFonoaudiologia',
    TERAPIA_OCUPACIONAL = 'TerapiaOcupacional',
    MEDICINA = 'Medicina',
    LABOROTORIO_BACTERIOLOGO = 'LaboratorioBacteriologo',
    LABORATORIO_ENFERMERIA = 'LaboratorioEnfermeria',
    NUTRICION_GENERAL = 'NutricionGeneral',
    TRABAJO_SOCIAL_GENERAL = 'TrabajoSocialGeneral',
    PSICOLOGIA_GENERAL = 'PsicologiaGeneral',
}
